### ISSUE TITLE
[graphql-typescript-definitions] - create enum as ts type

### ISSUE THREAD

**Issue by davidsonsns** [Shopify/graphql-tools-web#98]
Is there any option to generate `enum` as typescript type?
I mean something like this https://graphql-code-generator.com/docs/plugins/typescript#enumsastypes-boolean-default-value-false.

for example:
```gql
enum Status {
    AVAILABLE
    UNAVAILABLE
}
```

instead of this:
```ts
enum Status {
    AVAILABLE: "AVAILABLE",
    UNAVAILABLE: "UNAVAILABLE"
}
```

could have a param to generate it:
```ts
type Status = "AVAILABLE" | "UNAVAILABLE"
```

**Comment by riyadhctg** [comment]
Not sure if this answers your question, but this from [Typescript doc ](https://www.typescriptlang.org/docs/handbook/enums.html) seems relevant:

_The first is that enum members also become types as well! For example, we can say that certain members can only have the value of an enum member:_

```
enum ShapeKind {
    Circle,
    Square,
}

interface Circle {
    kind: ShapeKind.Circle;
    radius: number;
}

interface Square {
    kind: ShapeKind.Square;
    sideLength: number;
}

let c: Circle = {
    kind: ShapeKind.Square, // Error! Type 'ShapeKind.Square' is not assignable to type 'ShapeKind.Circle'.
    radius: 100,
}

```
